# 플러그인 설정
plugins:
  - jekyll-remote-theme

# 원격 테마 설정 (minimal 테마로 변경)
remote_theme: pages-themes/minimal

# 사이트 기본 정보
title: AI 리부팅
name : Bits to Brains
description: 엔지니어의 AI 번역기
url: "https://james-hyeok-kim.github.io/Paper_Review_KR.io"
baseurl: "/Paper_Review_KR.io"

# Analytics
analytics:
  provider               : false # 구글 어날리틱스 등록 false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

# Site Author
author:
  name             : "Bits to Brains"
  avatar           : ""
  bio              : "엔지니어의 AI 번역기"
  location         : "South Korea"
  email            : "younghyeok25@gmail.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:younghyeok25@gmail.com

# Outputting
permalink: /:categories/:title/
paginate: 5 # 첫 페이지에보여줄 최근 게시물 수를 지정
paginate_path: /page:num/
timezone: Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # 블로그 댓글 기능 true
      share: true
      related: true

  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: true
      related: false
